eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:1521/dbName?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
#    default-property-inclusion: non_empty
  redis:
    host: 10.1.234.52
    password: opaas
  rabbitmq:
    host: localhost
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
    integration:
      enabled: false
    scheduled:
      skip-pattern: "^org.*HystrixStreamTask$"
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

logging:
  path: logs
  level:
    root: info
    com.aici: debug
    org.springframework:  info
    org.mybatis.spring: info




